<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="6.4700" tests="13" failures="10">
  <testsuite name="Root Suite" timestamp="2021-06-21T17:21:22" tests="0" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="stock_trades_api_medium" timestamp="2021-06-21T17:21:22" tests="13" file="J:\vsc workspace\Interview Ground\Cisco\81b6c1ce-ddf8-45bb-8e46-7c47b0e1c488\test\index.spec.js" time="6.4700" failures="10">
    <testcase name="stock_trades_api_medium should create a new trade of buy type" time="0.0930" classname="should create a new trade of buy type">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 500
    at Context.<anonymous> (test\index.spec.js:70:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should create a new trade of sell type" time="0.0200" classname="should create a new trade of sell type">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 201 but got 500
    at Context.<anonymous> (test\index.spec.js:77:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all the trades" time="0.0790" classname="should fetch all the trades">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test\index.spec.js:85:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if the type filter value does not exist" time="0.0660" classname="should fetch no trades if the type filter value does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test\index.spec.js:92:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all trades for a user" time="0.0510" classname="should fetch all trades for a user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test\index.spec.js:99:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch no trades if user filter value does not exist" time="0.0490" classname="should fetch no trades if user filter value does not exist">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test\index.spec.js:106:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all buy trades for a user" time="2.0100" classname="should fetch all buy trades for a user">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (J:\vsc workspace\Interview Ground\Cisco\81b6c1ce-ddf8-45bb-8e46-7c47b0e1c488\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (J:\vsc workspace\Interview Ground\Cisco\81b6c1ce-ddf8-45bb-8e46-7c47b0e1c488\test\index.spec.js)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch all sell trades for a user" time="0.0630" classname="should fetch all sell trades for a user">
      <failure message="expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500" type="AssertionError"><![CDATA[AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 500
    at Context.<anonymous> (test\index.spec.js:120:30)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should fetch a single trade" time="2.0070" classname="should fetch a single trade">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (J:\vsc workspace\Interview Ground\Cisco\81b6c1ce-ddf8-45bb-8e46-7c47b0e1c488\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (J:\vsc workspace\Interview Ground\Cisco\81b6c1ce-ddf8-45bb-8e46-7c47b0e1c488\test\index.spec.js)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 404 if the trade ID does not exist" time="2.0040" classname="should get 404 if the trade ID does not exist">
      <failure message="Timeout of 2000ms exceeded. For async tests and hooks, ensure &quot;done()&quot; is called; if returning a Promise, ensure it resolves. (J:\vsc workspace\Interview Ground\Cisco\81b6c1ce-ddf8-45bb-8e46-7c47b0e1c488\test\index.spec.js)" type="Error"><![CDATA[Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (J:\vsc workspace\Interview Ground\Cisco\81b6c1ce-ddf8-45bb-8e46-7c47b0e1c488\test\index.spec.js)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)]]></failure>
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a put request to /trades/:id" time="0.0070" classname="should get 405 for a put request to /trades/:id">
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a patch request to /trades/:id" time="0.0110" classname="should get 405 for a patch request to /trades/:id">
    </testcase>
    <testcase name="stock_trades_api_medium should get 405 for a delete request to /trades/:id" time="0.0100" classname="should get 405 for a delete request to /trades/:id">
    </testcase>
  </testsuite>
</testsuites>